name: Sync Deployments to AWS S3

on:
  push:
    branches:
      - deployments

permissions:
  id-token: write
  contents: read

jobs:
  sync-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # REMEMBER TO UPDATE YOUR ACCOUNT ID HERE
          role-to-assume: arn:aws:iam::318270725890:role/GitHubActionsS3SyncRole #change the account id to the proftask account
          aws-region: eu-central-1

      - name: Smart Sync (Only Changed Files)
        run: |
          # 1. Find newly added (A) or modified (M) JSON files
          CHANGED_FILES=$(git diff --name-only --diff-filter=AM HEAD^ HEAD | grep '\.json$' || true)
          
          for file in $CHANGED_FILES; do
            echo "Uploading $file..."
            aws s3 cp "./$file" "s3://fontys-config-master/$file" #change to proftask s3 bucket
          done
          
          # 2. Find deleted (D) JSON files to clean up S3 during Teardown
          DELETED_FILES=$(git diff --name-only --diff-filter=D HEAD^ HEAD | grep '\.json$' || true)
          
          for file in $DELETED_FILES; do
            echo "Removing $file from S3..."
            aws s3 rm "s3://fontys-config-master/$file" #change the account id to the proftask account
          done
